{"abstract":[{"text":"The authorization attempt failed for an unknown reason.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`internal`","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tsauthenticationerror\/internal(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationError"]]},"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationError\/internal(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`internal`"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?)","kind":"text"}],"title":"TSAuthenticationError.internal(_:)","symbolKind":"case","externalID":"s:19TSAuthenticationSDK0A5ErrorO8internalyACs0C0_pSgcACmF","role":"symbol","modules":[{"name":"TSAuthenticationSDK"}]},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"kind":"symbol","title":"TSAuthenticationSDK","role":"collection","url":"\/documentation\/tsauthenticationsdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthenticationError/internal(_:)":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"`internal`"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"TSAuthenticationError.internal(_:)","url":"\/documentation\/tsauthenticationsdk\/tsauthenticationerror\/internal(_:)","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationError\/internal(_:)","abstract":[{"text":"The authorization attempt failed for an unknown reason.","type":"text"}],"kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthenticationError":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/tsauthenticationsdk\/tsauthenticationerror","title":"TSAuthenticationError","navigatorTitle":[{"text":"TSAuthenticationError","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSAuthenticationError"}]}}}