{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"`internal`","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationError\/internal(_:)"},"abstract":[{"type":"text","text":"The authorization attempt failed for an unknown reason."}],"metadata":{"externalID":"s:19TSAuthenticationSDK0A5ErrorO8internalyACs0C0_pSgcACmF","title":"TSAuthenticationError.internal(_:)","modules":[{"name":"TSAuthenticationSDK"}],"role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`internal`"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationError"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tsauthenticationerror\/internal(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthenticationError":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationError","kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tsauthenticationerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSAuthenticationError","kind":"identifier"}],"title":"TSAuthenticationError","role":"symbol","navigatorTitle":[{"text":"TSAuthenticationError","kind":"identifier"}],"type":"topic","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthenticationError/internal(_:)":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`internal`","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?)"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthenticationerror\/internal(_:)","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationError\/internal(_:)","type":"topic","kind":"symbol","title":"TSAuthenticationError.internal(_:)","abstract":[{"text":"The authorization attempt failed for an unknown reason.","type":"text"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"abstract":[],"url":"\/documentation\/tsauthenticationsdk","kind":"symbol","title":"TSAuthenticationSDK","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","type":"topic","role":"collection"}}}