{"abstract":[{"type":"text","text":"The authorization attempt failed for an unknown reason."}],"metadata":{"title":"TSAuthenticationError.internal(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"`internal`","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?)","kind":"text"}],"symbolKind":"case","roleHeading":"Case","externalID":"s:19TSAuthenticationSDK0A5ErrorO8internalyACs0C0_pSgcACmF","modules":[{"name":"TSAuthenticationSDK"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`internal`"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tsauthenticationerror\/internal(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationError"]]},"sections":[],"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationError\/internal(_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"role":"collection","title":"TSAuthenticationSDK","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","kind":"symbol","abstract":[],"url":"\/documentation\/tsauthenticationsdk","type":"topic"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthenticationError":{"navigatorTitle":[{"text":"TSAuthenticationError","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSAuthenticationError","kind":"identifier"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthenticationerror","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationError","title":"TSAuthenticationError","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSAuthenticationError/internal(_:)":{"title":"TSAuthenticationError.internal(_:)","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSAuthenticationError\/internal(_:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The authorization attempt failed for an unknown reason."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`internal`"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"url":"\/documentation\/tsauthenticationsdk\/tsauthenticationerror\/internal(_:)"}}}