{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"TSWebAuthnError.internal(_:)","externalID":"s:19TSAuthenticationSDK15TSWebAuthnErrorO8internalyACs0E0_pSgcACmF","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"`internal`"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"modules":[{"name":"TSAuthenticationSDK"}],"roleHeading":"Case","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnError"]]},"abstract":[{"type":"text","text":"The authorization attempt failed for an internal reason."}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnerror\/internal(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnError\/internal(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`internal`","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnError":{"navigatorTitle":[{"text":"TSWebAuthnError","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnError"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnError","kind":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnerror","role":"symbol","title":"TSWebAuthnError"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnError/internal(_:)":{"url":"\/documentation\/tsauthenticationsdk\/tswebauthnerror\/internal(_:)","title":"TSWebAuthnError.internal(_:)","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnError\/internal(_:)","abstract":[{"type":"text","text":"The authorization attempt failed for an internal reason."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"`internal`","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"kind":"symbol","url":"\/documentation\/tsauthenticationsdk","identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","role":"collection","abstract":[],"title":"TSAuthenticationSDK","type":"topic"}}}