{"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnError\/internal(_:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The authorization attempt failed for an internal reason."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnerror\/internal(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`internal`"},{"kind":"text","text":"("},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"metadata":{"externalID":"s:19TSAuthenticationSDK15TSWebAuthnErrorO8internalyACs0E0_pSgcACmF","roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"`internal`","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"modules":[{"name":"TSAuthenticationSDK"}],"title":"TSWebAuthnError.internal(_:)"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnError"]]},"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"kind":"symbol","title":"TSAuthenticationSDK","role":"collection","url":"\/documentation\/tsauthenticationsdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnError/internal(_:)":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnError\/internal(_:)","type":"topic","abstract":[{"type":"text","text":"The authorization attempt failed for an internal reason."}],"title":"TSWebAuthnError.internal(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/tsauthenticationsdk\/tswebauthnerror\/internal(_:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"`internal`","kind":"identifier"},{"kind":"text","text":"("},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnError":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSWebAuthnError"}],"url":"\/documentation\/tsauthenticationsdk\/tswebauthnerror","kind":"symbol","navigatorTitle":[{"text":"TSWebAuthnError","kind":"identifier"}],"title":"TSWebAuthnError","type":"topic","abstract":[]}}}