{"kind":"symbol","identifier":{"url":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnError\/internal(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnError"]]},"abstract":[{"text":"The authorization attempt failed for an internal reason.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`internal`","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}]}]}],"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"`internal`"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"roleHeading":"Case","title":"TSWebAuthnError.internal(_:)","modules":[{"name":"TSAuthenticationSDK"}],"externalID":"s:19TSAuthenticationSDK15TSWebAuthnErrorO8internalyACs0E0_pSgcACmF","role":"symbol","symbolKind":"case"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/tsauthenticationsdk\/tswebauthnerror\/internal(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK":{"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK","url":"\/documentation\/tsauthenticationsdk","kind":"symbol","role":"collection","title":"TSAuthenticationSDK","type":"topic","abstract":[]},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnError":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSWebAuthnError"}],"type":"topic","url":"\/documentation\/tsauthenticationsdk\/tswebauthnerror","abstract":[],"title":"TSWebAuthnError","navigatorTitle":[{"text":"TSWebAuthnError","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnError","kind":"symbol","role":"symbol"},"doc://com.TransmitSecurity.TSAuthenticationSDK/documentation/TSAuthenticationSDK/TSWebAuthnError/internal(_:)":{"abstract":[{"text":"The authorization attempt failed for an internal reason.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"`internal`","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.TransmitSecurity.TSAuthenticationSDK\/documentation\/TSAuthenticationSDK\/TSWebAuthnError\/internal(_:)","title":"TSWebAuthnError.internal(_:)","url":"\/documentation\/tsauthenticationsdk\/tswebauthnerror\/internal(_:)","kind":"symbol","role":"symbol","type":"topic"}}}